# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-02 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='contents',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
