# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-21 08:35
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180221_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, help_text='경도, 위도 포맷으로 입력 바람', max_length=40, validators=[blog.models.lnglat_validator]),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Markdown 문법 사용 바람', verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='포스팅 제목을 최대 100자 이내로 입력해주세요.', max_length=100, verbose_name='제목'),
        ),
    ]
