# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-21 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180221_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='testfield',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='post',
            name='testtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
