# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-08 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='content',
            new_name='description',
        ),
    ]
